name: 'calc_action'
description: 'arithmetic calculations' 

inputs:
  userInput1:
    type: number
    description: 'number 1'
    required: true
  userInput2:
    type: number
    description: 'number 2'
    required: true
  operation:
    type: choice
    description: '*,+,/,-'
    required: true 
outputs:
  result:
    description: 'calculation result' 
    runs:
      using: 'composite'
      steps:
        run: |
          $result = ${{ inputs.num1 }}${{ inputs.operator }}${{ inputs.num2 }}
